  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.2
    container_name: trust-engine-wazuh-indexer
    hostname: wazuh-indexer
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.nodedn_whitelist=CN=wazuh-indexer"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./wazuh/config/wazuh-indexer/opensearch.yml:/usr/share/wazuh-indexer/opensearch.yml:ro
    ports:
      - "9201:9200"
    networks:
      - trust-engine-network
