# OpenSearch configuration for Wazuh Indexer
cluster.name: wazuh-indexer-cluster
node.name: wazuh-indexer
node.roles:
  - master
  - data
  - ingest

# Network configuration
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300

# Discovery configuration
discovery.type: single-node
cluster.initial_master_nodes:
  - wazuh-indexer

# Path configuration
path.data: /var/lib/wazuh-indexer
path.logs: /usr/share/wazuh-indexer/logs

# Memory settings
bootstrap.memory_lock: true

# Security settings (disabled for development)
plugins.security.disabled: true

# Performance settings
indices.memory.index_buffer_size: 10%
indices.memory.min_index_buffer_size: 48mb

# Thread pool settings
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Index settings
action.auto_create_index: "+wazuh*,+trust*,+telemetry*,+.opendistro*,+.opensearch*,-*"

# Disk usage thresholds
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# Compatibility settings
compatibility.override_main_response_version: true

# Logging
logger.org.opensearch.deprecation: WARN
