# Kibana configuration for Trust Engine - Minimal Setup
server.name: trust-engine-kibana
server.host: "0.0.0.0"
server.port: 5601

# Disable SSL for simplicity
server.ssl.enabled: false

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "trust-engine-elastic-password"
elasticsearch.ssl.verificationMode: none

# Security settings
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "trust-engine-kibana-encryption-key-32-chars"

# Basic settings
server.rewriteBasePath: false

# Logging - simple console logging
logging.root:
  level: info

# Performance settings
elasticsearch.requestTimeout: 30000
elasticsearch.shardTimeout: 30000

# Enable basic features
xpack.reporting.enabled: false
xpack.maps.enabled: true
xpack.ml.enabled: true

# Monitoring
xpack.monitoring.ui.container.elasticsearch.enabled: true

# Disable telemetry and news
newsfeed.enabled: false
telemetry.enabled: false
telemetry.optIn: false

# Session settings
xpack.security.session.idleTimeout: "8h"
xpack.security.session.lifespan: "24h"
